-- Drop existing admin user if exists and create new simple one
DELETE FROM auth.users WHERE email = 'admin@congregacao.local';
DELETE FROM public.profiles WHERE username = 'admin';

-- Insert admin user directly into auth.users
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'admin-user-id-12345',
  'authenticated',
  'authenticated',
  'admin@congregacao.local',
  crypt('admin123', gen_salt('bf')),
  NOW(),
  '',
  NOW(),
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider": "email", "providers": ["email"]}',
  '{"full_name": "Administrador"}',
  false,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  '',
  0,
  NULL,
  '',
  NULL,
  false,
  NULL
);

-- Insert profile for admin user
INSERT INTO public.profiles (
  id,
  user_id,
  username,
  full_name,
  role,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'admin-user-id-12345',
  'admin',
  'Administrador',
  'admin',
  NOW(),
  NOW()
) ON CONFLICT (username) DO NOTHING;